{% set name = "gds-gui" %}
{% set version = "2.19.7" %}

# dependencies
{% set gds_base_version = "2.19.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: 779b5e7ad20595b50cd07aa908722d68ed388434b6cb64a71787cce98688f83b

build:
  number: 2
  skip: true  # [win]

outputs:
  - name: gds-gui-crtools
    script: build-crtools.sh
    build:
      ignore_run_exports:
        # header needed only
        - gds-base-gdstrig
      run_exports:
        - {{ pin_subpackage("gds-gui-crtools", max_pin="x.x") }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - make
        - pkg-config
        - sysroot_linux-64 2.17  # [linux64]
      host:
        - gds-base >={{ gds_base_version }}
        - gds-base-crtools >={{ gds_base_version }}
        - root_base
      run:
        - gds-base >={{ gds_base_version }}
        - gds-base-crtools >={{ gds_base_version }}
        - root_base
    test:
      requires:
        - pkg-config
      commands:
        # basic file existence
        - test -f ${PREFIX}/include/gds/dttview/TLGMath.hh  # [unix]
        - test -f ${PREFIX}/lib/libRdttview${SHLIB_EXT}  # [unix]
        # check root extensions
        - root -b -l -x -q -e "gInterpreter->AddIncludePath(\"${PREFIX}/include/gds\"); gSystem->Load(\"libRdttview\");"  # [linux]
        - root -b -l -x -q -e "gInterpreter->AddIncludePath(\"${PREFIX}/include/gds\"); gSystem->Load(\"libRgdsplot\");"  # [linux]
        - root -b -l -x -q -e "gInterpreter->AddIncludePath(\"${PREFIX}/include/gds\"); gSystem->Load(\"libRligogui\");"  # [linux]
        # check pkg-config files
        - pkg-config --print-errors --exact-version {{ version }} gdsdttview  # [unix]
        - pkg-config --print-errors --exact-version {{ version }} gdsligogui  # [unix]
    about:
      home: https://wiki.ligo.org/Computing/DASWG/DMT
      dev_url: https://git.ligo.org/gds/gds.git
      license: GPL-2.0-only
      license_family: GPL
      license_file: COPYING
      summary: GDS control room tools
      description: |
        GDS control room tools and GUI libraries

about:
  home: https://wiki.ligo.org/Computing/DASWG/DMT
  dev_url: https://git.ligo.org/gds/gds.git
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: GDS GUI libraries
  description: |
    GDS control room tools and GUI libraries

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
